version: "2"
services:
  jenkins:
    image: jenkins:${JENKINS_TAG}
    ports:
      - 28080:8080
    volumes:
      - "jenkins:/var/jenkins_home"
    restart: always
  registry:
    image: registry:${REGISTRY_TAG}
    ports:
      - 25000:5000
    volumes:
      - "registry:/var/lib/registry"
    restart: always
volumes:
  jenkins:
  registry:
