version: "2"
services:
  nginx:
    image: nginx:${NGINX_TAG}
    ports:
      - 20080:80
      - 20443:443
    volumes:
      - "${DEPLOYMENT_ROOT}/trash/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:z"
      - "${DEPLOYMENT_ROOT}/trash/nginx/html:/usr/share/nginx/html:z"
      - "/etc/letsencrypt:/etc/certs"
    restart: always
  jenkins:
    image: jenkins:${JENKINS_TAG}
    ports:
      - 28080:8080
    volumes:
      - "jenkins:/var/jenkins_home"
    restart: always
volumes:
  jenkins:
