version: "3"
services:
  jenkins:
    image: ${JENKINS_IMAGE}
    ports:
      - 28080:8080
    volumes:
      - "jenkins:/var/jenkins_home:z"
      - "/var/run/docker.sock:/var/run/docker.sock:z"
    group_add:
      - root
    privileged: true
    restart: always
  registry:
    image: ${REGISTRY_IMAGE}
    ports:
      - 25000:5000
    volumes:
      - "registry:/var/lib/registry:z"
    restart: always
volumes:
  jenkins:
  registry:
